# ======================================================================================= #
#  _                _   _            __          __        _        _                     #
# | |              | | | |           \ \        / /       | |      | |                    #
# | |     ___  __ _| |_| |__   ___ _ _\ \  /\  / /__  _ __| | _____| |__   ___  _ __      #
# | |    / _ \/ _` | __| '_ \ / _ \ '__\ \/  \/ / _ \| '__| |/ / __| '_ \ / _ \| '_ \     #
# | |___|  __/ (_| | |_| | | |  __/ |   \  /\  / (_) | |  |   <\__ \ | | | (_) | |_) |    #
# |______\___|\__,_|\__|_| |_|\___|_|    \/  \/ \___/|_|  |_|\_\___/_| |_|\___/| .__/     #
#                                                                              | |        #
#                                                                              |_|        #
# ======================================================================================= #

# ðŸŒ Language Settings
#
# This defines the default language for the plugin.
# 
# ðŸ”¹ How it works:
# - The plugin will use the language file that matches this setting.
# - Language files are stored in the "lang" folder inside the plugin directory.
# - If the specified language file is missing, the plugin will default to English (en).
#
# ðŸ”¹ Available Languages (no download needed):
# - "en" â†’ English (default)
# - "de" â†’ German
#
# You can add more languages by placing additional translation files in the "lang" folder.
#
# Default: English (en)

language: en

# Chance of rotten flesh turning into leather
# Default: 100
# 100% always produces leather out of rotten flesh
leather-chance: 100

# Speed, how long the rotten meat should cook. (ticks it takes to cook the leather)
# Default: 200 (10s) - lower numbers means faster cooking (20 ticks = 1s)
# 200 takes about as long as it takes to turn wood into coal.
cook-speed: 200

# Indicates how many XP a melting process produces.
# Default: 5
# A normal melting process normally produces between 3-5 xp. 
xp-gain: 5